name: dart_china
description: The official mobile app of dart-china.org, built with flutter.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  discourse_api:
    git:
      url: git@github.com:jarontai/discourse_api.git
  full_screen_image:
    git:
      url: git@github.com:jarontai/full_screen_image.git
      ref: jarontai
  badges: ^2.0.1
  bloc: ^7.0.0
  bugly_crash: ^0.0.6
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.1
  equatable: ^2.0.2
  flutter_bloc: ^7.0.0
  flutter_easyloading: ^3.0.0
  flutter_markdown: ^0.6.1
  flutter_zoom_drawer: ^2.0.2+4
  get_it: 7.1.3
  html_editor_enhanced: ^2.2.0
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  package_info_plus: ^1.0.3
  path_provider: ^2.0.1
  reactive_forms: ^10.4.1
  result_type: ^0.1.0
  rxdart: ^0.27.1
  share_plus: ^2.1.4
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.6
  flutter_dotenv: ^5.0.0

# dependency_overrides:
#   discourse_api:
#     path: ../../discourse_api
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.2
  injectable_generator: null
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo_dart.png
    - assets/icon/logo_dart_ios.png
    - .env

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icon/logo_dart.png"
  image_path_ios: "assets/icon/logo_dart_ios.png"
